export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const SET_FILTER_NAME = "SET_FILTER_NAME";
export const SET_FILTER_TAGS = "SET_FILTER_TAGS";
export const FILTER_DATA = "FILTER_DATA";
export const ADD_DATA = "ADD_DATA";